# Site
name: "The Library by StreamSounds"
title: "The Library by StreamSounds"
description: "A collection of tips and advice for streamers by the StreamSounds community."
logo: 'assets/images/logo.webp'
favicon: 'assets/images/logo.webp'
image-location: 'assets/images/'
baseurl: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
future: false

streamsounds:
  discord: https://discord.streamsounds.tv
  instagram: https://www.instagram.com/streamsoundstv
  twitter: https://www.twitter.com/streamsoundstv
  youtube: https://www.youtube.com/channel/UC3rEHGEUyd3kVuPyWoXi1SQ

# Authors
authors:
  ogjunkyard:
    name: OGJunkyard
    display_name: OGJunkyard
    avatar: 'assets/images/OGFace.webp'
    email: ogjunkyard@gmail.com
    stream: https://twitch.tv/OGJunkyard
    web: https://twitch.tv/OGJunkyard
    twitter: https://twitter.com/OGJunkyard
    description: "Founder of StreamSounds"
  flavius:
    name: Flavius
    display_name: Flavius
    avatar: 'assets/images/Flavorful_Logo.webp'
    email: flaviuscreations@gmail.com
    stream: https://www.twitch.tv/FlavCreations
    web: https://www.twitch.tv/FlavCreations
    twitter: https://twitter.com/FlavCreations
    description: "Co-Founder of The Library by Stream Sounds"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Sitemap
url: "https://library.streamsounds.tv"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
